# Generated by Django 3.2.3 on 2021-05-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_rental_rental_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(auto_now=True),
        ),
    ]
