# Generated by Django 3.2.3 on 2021-05-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20210530_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(),
        ),
    ]
