# Generated by Django 3.2.3 on 2021-06-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0002_auto_20210602_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gifs',
        ),
    ]
