# Generated by Django 3.2.3 on 2021-06-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0003_remove_category_gifs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gif',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='gifs',
            field=models.ManyToManyField(to='gifs.Gif'),
        ),
    ]
