# Generated by Django 3.2.3 on 2021-06-02 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0004_auto_20210602_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gifs',
            field=models.ManyToManyField(related_name='categories', to='gifs.Gif'),
        ),
        migrations.CreateModel(
            name='Uploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_image', models.ImageField(upload_to='upload/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifs.gif')),
            ],
        ),
    ]
