# Generated by Django 3.2.3 on 2021-06-03 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0006_auto_20210603_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='uploader_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifs.gif', to_field='uploader_name'),
        ),
    ]
