# Generated by Django 3.2.3 on 2021-06-03 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0007_auto_20210603_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploader',
            name='id',
        ),
        migrations.AlterField(
            model_name='gif',
            name='uploader_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifs.uploader'),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
