# Generated by Django 3.2.3 on 2021-06-03 10:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0008_auto_20210603_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploader',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gif',
            name='uploader_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifs.uploader', to_field='name'),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
