# Generated by Django 3.2.3 on 2021-06-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0009_auto_20210603_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='uploader',
            constraint=models.UniqueConstraint(fields=('name',), name='unique'),
        ),
    ]
