# Generated by Django 3.2.3 on 2021-06-03 10:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0010_auto_20210603_1354'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uploader',
            name='unique',
        ),
        migrations.RemoveField(
            model_name='uploader',
            name='id',
        ),
        migrations.AddField(
            model_name='uploader',
            name='uploader_id',
            field=models.IntegerField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gif',
            name='uploader_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifs.uploader'),
        ),
    ]
