# Generated by Django 3.2.3 on 2021-06-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0011_auto_20210603_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='uploader_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
