# Generated by Django 3.2.3 on 2021-06-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0013_alter_gif_uploader_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gif',
            constraint=models.UniqueConstraint(fields=('uploder_name',), name='unique_uploader'),
        ),
    ]
