# Generated by Django 3.2.3 on 2021-06-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0014_gif_unique_uploader'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gif',
            name='unique_uploader',
        ),
        migrations.AlterField(
            model_name='gif',
            name='uploader_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
