# Generated by Django 3.2.3 on 2021-06-03 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0015_auto_20210603_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploader',
            name='uploader_id',
        ),
        migrations.AddField(
            model_name='uploader',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
